apiVersion: v2
name: opennebula
description: A Helm chart for OpenNebula cloud management platform
type: application
version: 0.2.5
appVersion: "7.2.0"
home: https://github.com/pablodelarco/opennebula-helm
maintainers:
  - name: opennebula
    url: https://github.com/pablodelarco/opennebula-helm
keywords:
  - opennebula
  - cloud
  - virtualization

dependencies:
  - name: mariadb
    version: "~24.0"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: mariadb.enabled
